spring:
    application:
        name: project_jenkins
    datasource:
        url: jdbc:h2:mem:djum
        username:  sa
        password: password 
        driver-class-name: org.h2.Driver 
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                enable_lazy_load_no_trans : true
        database: mysql
        database-platform: org.hibernate.dialect.H2Dialect 